# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional Subscription (70f59e87-157b-4a3f-96e8-bae1144aa0b3)'
    subscriptionId: '70f59e87-157b-4a3f-96e8-bae1144aa0b3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myapp'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bwolanczyk87/app-service-web-nodejs-get-started/azure-pipelines-storageWithSAS/ArmTemplates/storageAccount.json'
    overrideParameters: '-storageAccountName myapp66sa'
    deploymentMode: 'Incremental'
    deploymentOutputs: storageAccountNameOutput

- task: ARM Outputs@5
  inputs:
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Visual Studio Professional Subscription (70f59e87-157b-4a3f-96e8-bae1144aa0b3)'
    resourceGroupName: 'myapp'
    prefix: 'sat'
    outputNames: 'storageAccountNameOutput'
    whenLastDeploymentIsFailed: 'fail'


- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional Subscription (70f59e87-157b-4a3f-96e8-bae1144aa0b3)'
    subscriptionId: '70f59e87-157b-4a3f-96e8-bae1144aa0b3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'myapp'
    location: 'Central US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/bwolanczyk87/app-service-web-nodejs-get-started/azure-pipelines-storageWithSAS/ArmTemplates/keyVoultWithSAS.json'
    overrideParameters: '-storageAccountName $(sat_storageAccountName) -tenantID 866b717c-31b3-49d8-92b3-9645d41ca9ef'
    deploymentMode: 'Incremental'


  
  