# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Visual Studio Professional Subscription(70f59e87-157b-4a3f-96e8-bae1144aa0b3)'
    subscriptionId: '70f59e87-157b-4a3f-96e8-bae1144aa0b3'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'IaC'
    location: 'Central US'
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/infrastructureAsCode.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/ArmTemplates/infrastructureAsCode.parameters.json'
    deploymentMode: 'Incremental'
    deploymentName: 'IaC_deployment'
    deploymentOutputs: 'armTemplateContainerUri'

- task: PowerShell@2
  inputs:
    filePath: '$(System.DefaultWorkingDirectory)/ParseArmDeploymentOutput.ps1'
    arguments: '-armOutputString ''$(armTemplateContainerUri)'''

- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Professional Subscription(70f59e87-157b-4a3f-96e8-bae1144aa0b3)'
    scriptType: 'batch'
    scriptLocation: 'inlineScript'
    inlineScript: |
      azcopy copy '$(System.DefaultWorkingDirectory)/ArmTemplates' '$(armTemplateContainerUri) --recursive
  
