# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:  
  # Environment name
  environmentTestName: 'QAEnv'
  environmentDevName: 'DevEnv'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Validation
  displayName: Validation sources stage
  jobs:
  - job: TempaltesValidation
    steps:
      - task: AzureResourceManagerTemplateDeployment@3
        displayName: 'Validate webAppService template'
        inputs:
          deploymentScope: 'Resource Group'
          azureResourceManagerConnection: 'ArmTemplatesServiceConnection'
          subscriptionId: '70f59e87-157b-4a3f-96e8-bae1144aa0b3'
          action: 'Create Or Update Resource Group'
          resourceGroupName: 'myapp'
          location: 'Central US'
          templateLocation: 'Linked artifact'
          csmFile: 'ArmTemplate/webAppService.json'
          deploymentMode: 'Validation'        
