apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: bwolanczykmyapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bwolanczykmyapp  
    spec:
      containers:
        - name: bwolanczykmyapp  
          image: yudmivr5ulpmcacr.azurecr.io/bwimage 
          ports:
          - containerPort: 5000
